# vim: tabstop=2 softtabstop=0 expandtab shiftwidth=2 smarttab
---
name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

# optimize for size
env:
  CFLAGS: "-Os"
  CPPFLAGS: "-Os"
  CXXFLAGS: "-Os"
  LDFLAGS: "-Os"

jobs:
  kernel:
    runs-on: [linux]
    steps:
      - uses: actions/checkout@v2.0.0
      - name: Checking out the kernel source 5.4.y
        uses: actions/checkout@v2.0.0
        with:
          repository: gregkh/linux
          ref: linux-5.4.y
          path: linux
      - name: Install the build dependencies
        run: |
          sudo apt-get -y update
          sudo apt-get -y install flex bison
      - name: Configure the kernel
        run: cp linux.config linux/.config
      - name: Tiny up the kernel config
        run: make tinyconfig
        working-directory: linux
      - name: Building the kernel
        run: make
        working-directory: linux
      - name: Building the kernel headers
        run: make headers_install
        working-directory: linux
      - name: Upload the kernel
        uses: actions/upload-artifact@v1.0.0
        with:
          name: linux-kernel
          path: linux/arch/x86/boot/bzImage
      - name: Upload the kernel headers
        users: actions/upload-artifact@v1.0.0
        with:
          name: linux-kernel-headers
          path: linux/usr/include
  uclibc:
    needs: kernel
    runs-on: [linux]
    steps:
      - uses: actions/checkout@v2.0.0
      - name: Checking out µClibc-ng
        uses: actions/checkout@v2.0.0
        with:
          repository: wbx-github/uclibc-ng
          ref: v1.0.32
          name: uclibc-ng
      - name: Configuring µClibc-ng
        run: cp uclibc-ng.config uclibc-ng/.config
